const Types = {
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
  DELETE_QUANTITY_PRODUCT_TO_CART: 'DELETE_QUANTITY_PRODUCT_TO_CART',
  DELETE_ALL_QUANTITIES_PRODUCT_TO_CART: ' DELETE_ALL_QUANTITIES_PRODUCT_TO_CART',
  EMPTY_CART: 'EMPTY_CART',
  GET_PRODUCTS: 'GET_PRODUCTS',
};

export default Types;
